name: Make Mastodon Post

on:
  workflow_dispatch:
  schedule:
    - cron:  '7 7 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p poster
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          MASTODON_DOMAIN: "https://botsin.space"
